variable "name" {}
variable "ami" {}
variable "instance_type" {}
variable "security_groups" {}
variable "subnets" {}
variable "number_of_instances" {}
variable "tags" {}
variable "iam_instance_profile" {}
variable "key_name" {}